# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new beta version to Google Play"
  lane :beta do
    upload_to_play_store(
        track: 'beta',
        package_name: 'tenso.app',
        metadata_path: './fastlane/metadata/android',
        json_key: './fastlane/service_account.json',
        skip_upload_apk: true,
        skip_upload_aab: false,
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        validate_only: false,
        check_superseded_tracks: false,
        timeout: 300,
        deactivate_on_promote: true
    )
  end

  desc "Release a new version to Google Play"
  lane :release do
    upload_to_play_store(
        track: 'production',
        package_name: 'tenso.app',
        metadata_path: './fastlane/metadata/android',
        json_key: './fastlane/service_account.json',
        skip_upload_apk: true,
        skip_upload_aab: false,
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_changelogs: false,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        validate_only: false,
        check_superseded_tracks: false,
        timeout: 300,
        deactivate_on_promote: true
    )
  end
end
